spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  run:
    # https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/#cross-origin-resource-sharing
    cors:
      enabled: true
      # To support both HTTP authentication and CORS, allowed-origins must not be *
      allowed-origins: "http://localhost:[*],https://*.gurunetwork.ai,https://*.dex.guru,file://"
  authorization:
    enabled: true
    tenant-check-enabled: true
  webapp:
    index-redirect-enabled: true
#  default-serialization-format: application/json
server.port: 8080

# health check
management.endpoints.web.exposure.include: prometheus,health
management.health.defaults.enabled: false
management.endpoints.enabled-by-default: true
management.endpoint.health.enabled: true
#management.endpoints.web.base-path: /
#management.endpoints.web.path-mapping.health: health_check
management.endpoint.health.show-details: always

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
